config/routes.rb
Rails.application.routes.draw do
  root to: 'subjects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subjects do 
    resources :sources, only: [:create, :show]
  end

  resources :sources, only: [:destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :subject
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :content, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :sources, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :destroy]
  def new
    @source = Source.new
  end

  def create
    @source = Source.create(source_params)
    @source.subject = Subject.find(params[:subject_id])
    @subject = Subject.find(params[:subject_id])
    if @source.save
      respond_to do |format|
        format.html { redirect_to subject_path(@subject) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def show
  end

  def destroy
    @source.destroy
    redirect_to subject_path(@source.subject)
  end

private

  def source_params
    params.require(:source).permit(:id, :name, :content, :subject_id)
  end

  def set_source
    @source = Source.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :destroy]

  def index
    @subjects = Subject.all
  end

  def show
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to subjects_path
    else
      respond_to do |format|
      format.json { render :new}
      format.js
      end
    end
  end
  
  def destroy
    @subject.destroy
    redirect_to subjects_path
  end
  
  private
  
  def subject_params
    params.require(:subject).permit(:id, :name)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestHoggo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to subjects_path, class: "navbar-brand" do %>
    <%= image_tag "hoggo_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", subjects_path, class: "nav-link" %>
        </li>
    </ul>
  </div>
</div>


  

app/views/sources/_source.html.erb
<li class="list-group-item list-group-item-action mt-1 d-flex justify-content-between">
  <div class="d-flex flex-column bd-highlight">
    <div class="d-flex justify-content-between">
      <div class="bd-highlight"><%= link_to source.name, subject_source_path(@subject, source) %></div>
      <div>
            <%= link_to source_path(source),
                      method: :delete,
                      remote: true,
                      :data => { :confirm => "Are you sure you want to delete the source '#{source.name}' ?" } do %>
                        <i class="fas fa-trash"></i>
                      <% end %>
      </div>
    </div>
    <div class="bd-highlight"><%= truncate source.content, length: 150 %></div>
    <div class="bd-highlight small"><%= link_to 'read more and rewrite', subject_source_path(@subject, source) %></div>
  </div>
</li>

app/views/sources/_source_form.html.erb
<%= simple_form_for([subject, source], remote: true) do |f| %>
  <div class="form-group mb-0">
    <%= f.input :name, label: false, placeholder: "Source title", class:"form-control" %>
    <%= f.input :content, as: :text, label: false, placeholder: "Content"%>
    <%= f.submit "Submit", class: "btn btn-primary mt-2" %>
  <% end %>
  </div>

app/views/sources/create.js.erb
function addSource(source) {
  const sourcesCont = document.querySelector("#sources-cont");
  sourcesCont.insertAdjacentHTML('beforeend', source);
}

<%# clear the input form  %>
function clearInput() {
  const inputField = document.querySelector("#source_content");
  inputField.value = "";

  const titleField = document.querySelector("#source_name")
  titleField.value = "";
}

addSource('<%= j render "sources/source", source: @source %>')
clearInput()

app/views/sources/show.html.erb
<div class="container">
<%= link_to subject_path(@source.subject_id) do  %>
  <i class="fas fa-arrow-left"></i>
  <% end %>
  <div class="card mt-3">
    <div class="card-body">
      <h5 class="card-title title"><%= @source.name %></h5>
      <p class="card-text" id="source-content"><%= @source.content %></p>
    
    
    </div>
  </div>
  
  <button class="btn btn-primary mt-3" id="rewrite-button">Rewrite this source</button>
  <div class="spinner-border d-none" role="status">
    <span class="visually-hidden"></span>
  </div>
  
  <div class="rewrite-container">
    
  </div>
</div>

app/views/subjects/_subject_form.html.erb
<div class="form-group">
  <%= simple_form_for(Subject.new, remote: true) do |f| %>
    <%= f.input :name, label: "Enter a new subject", class:"form-control" %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/subjects/create.js.erb
function addSubject(source) {
  const subjectsCont = document.querySelector("#subjects-cont");
  subjectsCont.insertAdjacentHTML('beforeend', source);
}

<%# clear the input form  %>
function clearInput() {
  const inputField = document.querySelector("#subject_content");
  inputField.value = "";
}

addSource('<%= j render "sources/source", source: @source %>')
clearInput()

app/views/subjects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-12">
      <h1 class="mt-3 title">Welcome to the Hoggo content creator tool</h1>
      <h4 class="mt-3 title">Choose a subject, enter a source and use our tool to rewrite it</h4>
      <h5 class="mt-3">List of existing subjects: </h5>
      <% if @subjects.count.zero? %>
        <p>No subjects yet, add a new one !</p>
      <% else %>
      <ul class="list-group mt-3">
      <% @subjects.each do |subject| %>
        <li class="list-group-item list-group-item-action mt-1 d-flex justify-content-between">
          <%= link_to subject.name, subject_path(subject.id)  %>
          <div class="delete">
          <%= link_to subject_path(subject),
                    method: :delete,
                    remote: true,
                    :data => { :confirm => "Are you sure you want to delete the subject '#{subject.name}' ?" } do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
          </div>
        </li>
      <% end %>
      </ul>
      <% end %>
      <h5 class="mt-5">Didn't find the subject you were looking for ? Create a new one:</h5>
      <%= render "subject_form" %>
    </div>
  </div>
</div>

app/views/subjects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8">
    <%= link_to subjects_path do  %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
    <h1 class="mt-3 titleg"><%= @subject.name %></h1>
    <p>Click on a source to view it and rewrite it</p>
    <ul class="list-group mt-3" id="sources-cont">
      <% @subject.sources.each do |source| %>
        <%= render 'sources/source', source: source, subject: @subject %>
      <% end %>
    </ul>
      <h3 class="mt-5">Add a new source</h3>
      <%= render 'sources/source_form', subject: @subject, source: Source.new %>
    </div>
  </div>
</div>